spring:
  datasource:
    url: jdbc:mysql://localhost:3306/template?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#  cache:
#    type: redis
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会 新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
      ddl-auto: update
      naming:
        #指定jpa的自动表生成策略，驼峰自动映射为下划线格式7
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
#  data:
#    redis:
#      host: localhost
#      port: 6379
  sql:
    init:
      mode: always # 初始化数据
      continue-on-error: true
jwt:
  expire: 43200 #12小时 12 * 60 * 60 S
  tokenHeader: Authorization #JWT存储的请求头
  tokenHead: Bearer  #JWT负载中拿到开头
logging:
  file:
    path: logs
